# Generated by Django 5.2 on 2025-04-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citoyen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='Reclamation_fiche/', verbose_name='Evidence'),
        ),
    ]
