# Generated by Django 5.2 on 2025-04-13 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citoyen', '0002_complaint_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='Citoyen.category'),
        ),
    ]
