# Generated by Django 5.2 on 2025-05-02 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citoyen', '0003_alter_problem_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='phone',
        ),
        migrations.AddField(
            model_name='citizen',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citizens', to='Citoyen.municipality', verbose_name='Municipalité de résidence'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='nni',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='NNI'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='Citoyen.municipality'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type__in': ['ADMIN', 'SUPERADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'CITIZEN'}, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse e-mail'),
        ),
    ]
