# Generated by Django 5.2 on 2025-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citoyen', '0006_problem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
