# Generated by Django 5.2 on 2025-05-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citoyen', '0009_problem_document_problem_video_problem_voice_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Reclamation_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Reclamation_videos/', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='voice_record',
            field=models.FileField(blank=True, null=True, upload_to='Reclamation_voice/', verbose_name='Voice Record'),
        ),
    ]
