# Generated by Django 5.2 on 2025-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citoyen', '0010_complaint_comment_complaint_photo_complaint_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo de profil'),
        ),
    ]
