"""
Django settings for Belediyti project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Added for MEDIA_ROOT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CHINGUISOFT_VALIDATION_KEY = os.getenv('CHINGUISOFT_VALIDATION_KEY', 'ciSPuRWNvl4HUyUP')
CHINGUISOFT_VALIDATION_TOKEN = os.getenv('CHINGUISOFT_VALIDATION_TOKEN', '9PfCCPEdLf2HkTWtSNMacYWz9JfByW3F')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jgbv+g2ziypwb7hl^cx920f-h8*lt_ixh0i*o5=!-3i=7s0b1('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CORS_ORIGIN_ALLOW_ALL = True  # ONLY for development
# settings.py
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5000",  # Example Flutter web origin
    "http://127.0.0.1:8000",  # Django backend (if you access it directly)
   "http://10.0.2.2:8000",  # Add other origins as needed (e.g., your production Flutter web URL)
]
ALLOWED_HOSTS = ['127.0.0.1',
                 '192.168.163.95',
                 '192.168.163.95',
                 '192.168.163.198',
                 "http://10.0.2.2:8000", 
                 '*', # Allow all hosts for now, refine for production
                 ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Citoyen', # Your app
    'django.contrib.humanize',
    'super_admin',
    'Muni_admin',
    'rest_framework',
    'corsheaders',
    
    'rest_framework.authtoken',  # This was the missing piece
 

] 
# settings.py
import os

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',  # Set the logging level here
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'Citoyen': {  # Logger for your app ("Citoyen")
            'handlers': ['console'],
            'level': 'DEBUG', # Set Logger  level
            'propagate': True, # Don't propagate to root logger if False
        },
        'django': {  # Set logging level to info, for Django log
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
# settings.py
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'  # Or use IsAuthenticated for production
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For browsable API
        'rest_framework.authentication.TokenAuthentication',  # For Flutter app
    ],
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Belediyti.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Belediyti.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr' # Changed to French

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Custom User Model
AUTH_USER_MODEL = 'Citoyen.User'

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = (
    'Citoyen.backends.PhoneOrEmailBackend', # Your custom backend
    'django.contrib.auth.backends.ModelBackend', # Default Django backend (needed for admin login)
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Add STATIC_ROOT for collectstatic if needed for deployment
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Define where media files are stored

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login' # Redirect to login page after logout
LOGIN_REDIRECT_URL = 'redirect_user' # Redirect to a view that handles role-based redirection

# Ensure upload directories exist (optional, good practice)
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)
if not os.path.exists(os.path.join(MEDIA_ROOT, 'problem_photos')):
    os.makedirs(os.path.join(MEDIA_ROOT, 'problem_photos'))
if not os.path.exists(os.path.join(MEDIA_ROOT, 'Reclamation_fiche')):
    os.makedirs(os.path.join(MEDIA_ROOT, 'Reclamation_fiche'))


